In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("Merged_data.csv")
df=df.drop("States / Union Territories",axis=1)

In [3]:
df

,States / Union Territories,All Categories - Classes I-V - Boys_a1,All Categories - Classes I-V - Girls_a1,All Categories - Classes I-V - Total_a1,All Categories - Classes I-VIII - Boys_a1,All Categories - Classes I-VIII - Girls_a1,All Categories - Classes I-VIII - Total_a1,All Categories - Classes I-X - Boys_a1,All Categories - Classes I-X - Girls_a1,All Categories - Classes I-X - Total_a1,...,Scheduled Caste - Classes I-X - Total_a4,Scheduled Tribe - Classes I-V - Boys_a4,Scheduled Tribe - Classes I-V - Girls_a4,Scheduled Tribe - Classes I-V - Total_a4,Scheduled Tribe - Classes I-VIII - Boys_a4,Scheduled Tribe - Classes I-VIII - Girls_a4,Scheduled Tribe - Classes I-VIII - Total_a4,Scheduled Tribe - Classes I-X - Boys_a4,Scheduled Tribe - Classes I-X - Girls_a4,Scheduled Tribe - Classes I-X - Total_a4
0,Andhra Pradesh,16.03,15.05,15.55,39.97,41.35,40.65,60.12,61.38,60.73,...,49.682219,35.531365,38.219769,36.846124,60.527942,64.525857,62.489432,71.627090,73.771688,72.671474
1,Arunachal Pradesh,41.80,39.71,40.84,44.87,43.31,44.16,63.39,62.43,62.95,...,100.000000,44.610560,42.697706,43.706119,54.374595,48.360801,51.622148,63.636364,63.338493,63.499496
2,Assam,78.67,78.67,78.67,68.21,68.35,68.28,78.47,79.55,78.97,...,44.350000,26.849619,24.509333,25.682091,49.680358,57.147395,53.393297,44.350000,44.350000,44.350000
3,Bihar,47.79,47.20,47.54,60.16,55.41,58.33,74.46,74.41,74.44,...,79.808706,31.600055,19.812514,27.122428,59.144221,47.005578,54.786912,72.174377,68.970737,71.065613
4,Chhattisgarh,26.16,26.91,26.52,37.86,37.19,37.54,56.25,56.06,56.17,...,58.972359,38.443508,42.130017,40.261195,45.389049,49.540873,47.414103,63.262592,62.016525,62.676454
5,Goa,42.27,42.27,42.27,42.27,42.27,42.27,36.20,32.93,34.61,...,49.793388,28.180000,28.180000,28.180000,28.180000,28.180000,28.180000,28.180000,28.180000,28.180000
6,Gujarat,39.11,3.30,25.87,46.36,40.75,44.29,56.24,62.25,58.84,...,64.548290,50.922077,44.556154,48.034453,69.397358,71.179778,70.205869,79.702995,75.160856,77.642676
7,Haryana,10.51,25.16,5.20,20.60,1.50,11.93,36.31,23.77,30.50,...,21.964621,10.210000,10.210000,10.210000,10.210000,10.210000,10.210000,10.210000,10.210000,10.210000
8,Himachal Pradesh,2.25,3.61,2.90,16.19,0.89,16.19,17.63,21.93,19.73,...,32.543864,0.027397,11.070000,11.070000,11.070000,11.070000,11.070000,0.258918,4.059579,2.144928
9,Jammu and Kashmir,1.97,2.41,2.18,28.51,20.94,25.24,42.70,38.01,40.65,...,26.700000,27.941023,31.883530,29.766084,58.495551,67.990585,62.679215,26.700000,26.700000,26.700000
10,Jharkhand,22.37,18.76,20.70,55.83,65.82,60.25,80.14,82.32,81.10,...,72.260417,39.639701,35.021927,37.481230,60.473987,49.414210,55.768809,80.804209,78.510411,79.777537
11,Karnataka,4.92,3.45,4.21,30.29,30.11,30.20,50.36,49.15,49.79,...,55.556160,6.914938,6.852172,6.884650,24.232048,29.706219,26.877365,47.510506,48.329375,47.905541
12,Kerala,18.10,18.10,18.10,18.10,18.10,18.10,18.10,18.10,18.10,...,6.204408,14.690000,14.690000,14.690000,9.086809,8.453940,8.773327,31.166295,27.091633,29.149056
13,Madhya Pradesh,21.02,19.23,20.18,30.89,29.53,30.27,53.59,62.84,57.64,...,43.200333,40.620334,33.320699,37.105723,38.575097,33.380374,36.133974,58.653979,71.869098,64.622288
14,Maharashtra,19.53,22.93,21.16,25.44,28.64,26.97,41.22,46.48,43.75,...,38.310594,23.733190,17.906470,21.119530,42.342707,46.756385,44.443075,65.666336,74.484119,69.846190
15,Manipur,39.55,45.19,42.31,42.92,44.94,43.90,58.91,57.06,58.03,...,49.430000,47.520408,55.367260,51.289721,74.262705,75.725500,74.961641,49.430000,49.430000,49.430000
16,Meghalaya,52.53,51.05,51.79,70.44,65.90,68.19,78.36,76.15,77.26,...,78.263244,57.502540,51.516274,54.605909,75.652320,71.988987,73.815520,81.270921,77.804591,79.575449
17,Mizoram,31.75,35.22,33.43,46.41,46.79,46.60,70.16,66.45,68.41,...,43.380000,37.574011,39.243604,38.383920,38.230610,36.461794,37.381544,55.471213,52.628407,54.078352
18,Nagaland,40.65,40.42,40.54,47.13,47.30,47.22,68.34,66.84,67.61,...,51.610000,40.522072,39.005562,39.816049,43.424565,38.351204,41.097811,70.315021,66.529046,68.549227
19,Odisha,33.33,32.89,33.12,59.07,53.98,56.92,68.29,65.76,67.18,...,75.111888,25.177787,18.560826,22.102357,73.993216,75.259172,74.592390,86.415789,84.546486,85.615278
20,Punjab,35.48,35.48,35.48,35.48,35.48,35.48,43.16,43.24,43.20,...,55.689879,25.470000,25.470000,25.470000,25.470000,25.470000,25.470000,25.470000,25.470000,25.470000
21,Rajasthan,49.33,52.01,50.57,59.32,57.89,58.77,69.90,74.50,71.69,...,74.511524,47.751908,51.225154,49.375185,59.545035,68.884213,63.998420,78.189022,80.740317,79.307296
22,Sikkim,41.97,31.55,36.95,52.99,39.41,46.41,81.99,82.53,82.26,...,74.277457,26.190476,11.086889,18.809922,54.964639,39.130435,47.250834,58.313018,44.709544,51.721538
23,Tamil Nadu,30.30,30.30,30.30,30.30,30.30,30.30,41.44,38.28,39.92,...,10.725988,4.362416,17.630000,17.630000,5.600176,17.630000,17.630000,34.220297,29.230501,31.872543
24,Tripura,24.64,20.07,22.49,49.49,45.53,47.61,71.68,70.33,71.04,...,47.773547,41.613196,41.479732,41.549203,60.431287,62.823875,61.577565,71.047438,72.221997,71.604084
25,Uttar Pradesh,41.18,33.96,37.82,30.64,9.48,22.67,19.70,4.73,14.11,...,57.239792,37.940000,37.940000,37.940000,27.943336,13.807585,22.227939,37.940000,37.940000,37.940000
26,Uttarakhand,35.84,31.82,33.90,24.74,27.08,25.91,33.31,39.64,36.46,...,50.155345,21.538725,9.904087,16.290444,33.979252,29.192300,31.602286,34.137136,37.687952,35.975733
27,West Bengal,30.75,28.83,29.81,60.88,57.69,59.33,70.42,73.77,72.00,...,66.153708,31.381224,24.825228,28.269595,49.377001,46.897567,48.169401,77.303495,70.911612,74.615477
28,Andaman and Nicobar Islands,13.61,10.05,11.89,13.66,16.91,15.22,26.78,26.19,26.50,...,17.910000,1.694915,17.910000,0.214133,23.004695,27.027027,24.874372,28.660436,34.957020,31.940299
29,Chandigarh,29.83,29.83,29.83,29.83,29.83,29.83,29.83,8.67,3.45,...,43.321833,71.600000,71.600000,71.600000,100.000000,100.000000,100.000000,71.600000,71.600000,71.600000
30,Dadra and Nagar Haveli,16.71,24.64,20.56,53.20,64.99,58.68,65.49,72.07,68.54,...,28.057554,1.267123,21.288014,11.970035,34.201443,48.812095,41.568139,60.175202,66.795966,63.252795
31,Daman and Diu,32.93,32.93,32.93,4.29,14.89,9.32,34.52,30.95,32.87,...,13.620000,1.990050,7.881773,4.950495,10.550459,33.649289,21.911422,13.620000,13.620000,13.620000
32,Delhi,21.05,7.80,0.50,14.86,20.17,17.44,29.60,35.23,32.34,...,21.680000,24.623656,23.458445,24.105012,21.680000,21.680000,21.680000,21.680000,21.680000,21.680000
33,Lakshadweep,7.42,3.69,5.59,16.67,15.14,15.94,26.09,14.17,20.47,...,100.000000,12.687585,5.037037,9.019886,16.765579,11.272142,14.131274,43.309002,22.922252,33.609694
34,Puducherry,8.79,8.79,8.79,8.79,8.79,8.79,8.36,3.28,5.91,...,7.974614,7.020000,7.020000,7.020000,7.020000,7.020000,7.020000,7.020000,7.020000,7.020000
35,INDIA,29.57,25.85,27.84,41.09,36.95,39.28,53.98,54.43,54.17,...,56.075883,37.171682,33.896803,35.625718,54.740729,55.369166,55.036406,70.624988,71.316129,70.938326

In [4]:
wcss=[]
from sklearn.cluster import KMeans

In [5]:
for i in range(1,11):
    km = KMeans(n_clusters=i)
    km.fit_predict(df)
    wcss.append(km.inertia_)

ValueError: could not convert string to float: 'Andhra Pradesh'